Update README file for buildroot external tree
TexasInstruments/buildroot-external-TI pull request #2
Opened 2024-08-05 04:34 UTC by paresh-bhagat12

Add overview about buildroot and buildroot external tree, steps to build a configuration and then flash and build an image.

2024-08-05 04:39 UTC, cshilwant commented on README.md
> +   [SK-AM62](https://www.ti.com/tool/SK-AM62) board. It builds and packages
Add all three variants of AM62x EVM we support on ti.com,

- [SK-AM62](https://www.ti.com/tool/SK-AM62)
- [SK-AM62B](https://www.ti.com/tool/SK-AM62B)
- [SK-AM62B-P1](https://www.ti.com/tool/SK-AM62B-P1)

2024-08-05 04:39 UTC, cshilwant commented on README.md
> +   [SK-AM62](https://www.ti.com/tool/SK-AM62) board. It builds and packages
Same comment as https://github.com/TexasInstruments/buildroot-external-TI/pull/2/files#r1703526320

2024-08-05 04:42 UTC, cshilwant commented on README.md
> +* [External Buildroot tree ST](https://github.com/bootlin/buildroot-external-st)
What have we referred from STM??
Ideally we should only refer Buildroot official steps

2024-08-05 05:12 UTC, cshilwant commented on README.md
> +### Steps to Build the Image
### Steps to Build the SD card Image

2024-08-05 05:12 UTC, cshilwant commented on README.md
> +## Flashing and booting the image
## Flashing and booting the SD card image

2024-08-05 05:16 UTC, cshilwant commented on README.md
> +Tools like balena-ethcer can also be used to flash this image.
Add Link to balena-etcher tool

2024-08-05 05:16 UTC, cshilwant commented on README.md
> +Tools like balena-ethcer can also be used to flash this image.
Tools like balena-ethcer can also be used to flash the SD card image.

2024-08-05 05:16 UTC, cshilwant commented on README.md
> +Tools like balena-ethcer can also be used to flash this image.
Does balena support .img format?

2024-08-05 05:18 UTC, cshilwant commented on README.md
> +Insert the SD Card in SD Card slot and power on the board (ex. AM62X-SK).
> (ex. AM62X-SK)

Same comment as https://github.com/TexasInstruments/buildroot-external-TI/pull/2/files#r1703526320

2024-08-05 05:23 UTC, cshilwant commented on README.md
> +
Add a section which says the prebuilt SD card image is already available to ti.com if users want to avoid building the entire image from sources.

2024-08-05 05:25 UTC, cshilwant commented on README.md
> +* [External Buildroot tree ST](https://github.com/bootlin/buildroot-external-st)
Add a section for **support** with E2E as reference

2024-08-05 06:00 UTC, cshilwant requested changes
Needs work

2024-08-05 12:11 UTC, paresh-bhagat12 commented on README.md
> +Tools like balena-ethcer can also be used to flash this image.
yes

2024-08-05 12:40 UTC, paresh-bhagat12 commented
you can view the  readme here https://github.com/TexasInstruments/buildroot-external-TI/tree/readme

2024-08-05 15:25 UTC, jsuhaas22 commented on README.md
> +Pre-build buildroot SD card images are available at:
`Pre-build` => `Pre-built`

2024-08-05 15:26 UTC, jsuhaas22 commented on README.md
> +interface configuration, legal information or documentation. For detailed
`or` => `and`

2024-08-05 15:28 UTC, jsuhaas22 commented on README.md
> +
We don't need the 2nd "directory" there.
Also `side-by-side`.

2024-08-05 15:29 UTC, jsuhaas22 commented on README.md
> +kernel, and bootloader. The build process can take sometime, depending on your
`sometime` => `some time`

2024-08-06 13:20 UTC, cshilwant commented on README.md
> +1. `ti_release_am62x_sk_defconfig` for non-RT-Linux
1. `ti_release_am62x_sk_defconfig` for Linux

2024-08-06 13:23 UTC, cshilwant requested changes
Needs Work

2024-08-07 05:31 UTC, cshilwant commented on README.md
> +## Prebuild SD card images
Prebuilt

2024-08-07 05:53 UTC, cshilwant approved these changes
LGTM!

2024-08-07 05:53 UTC, merged