am62x-sk: Add addidtional flags for optee-os
TexasInstruments/buildroot-external-TI pull request #8
Opened 2024-11-25 09:05 UTC by paresh-bhagat12

Enable additional flags for optee-os
- Enable SOFTWARE_PRNG to enable software based random number genrator. This also fixes low power mode failure on buildroot image.
- Set TEE_CORE_LOG_LEVEL to 1 for debug purpose.

2024-11-25 09:08 UTC, jsuhaas22 requested changes

2024-11-25 09:08 UTC, jsuhaas22 commented on configs/ti_release_am62x_sk_defconfig
> +BR2_TARGET_OPTEE_OS_ADDITIONAL_VARIABLES="CFG_WITH_SOFTWARE_PRNG=y CFG_TEE_CORE_LOG_LEVEL=1"
In Debian and Arago, we have only `CFG_TEE_CORE_LOG_LEVEL` for AM62x. `CFG_WITH_SOFTWARE_PRNG` is an argument only for AM62px.

2024-11-25 09:16 UTC, cshilwant requested changes
s/genrator/generator in commit message

2024-11-25 09:18 UTC, cshilwant requested changes
@paresh-bhagat12 

Better to explicitly mention linux as RT + LPM story is still not cracked

"This also fixes low power mode failure on buildroot `linux` image."

2024-11-25 12:23 UTC, cshilwant requested changes
s/debuggin/debugging

2024-11-26 04:19 UTC, cshilwant approved these changes

2024-11-26 04:21 UTC, jsuhaas22 approved these changes
LGTM

2024-11-26 04:22 UTC, merged